version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name LastWorkApp2 --s3-location s3://lastwork-s3-opeyt/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src